config/routes.rb
Rails.application.routes.draw do
  get 'carts/show'

  root 'products#index'
  resources :products
  resources :carts
  resources :orders

  post 'cart/add_to_cart' => 'carts#add_to_cart'
  post 'cart/edit_cart' => 'carts#edit_cart'
  devise_for :users, :controllers => { :registrations => 'users/registrations' }
  mount API::Root => '/'

end

app/models/cart.rb
class Cart < ActiveRecord::Base
	belongs_to :user
	has_many :products, :through => :cart_products
	has_many :cart_products
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
    @cart = Cart.find params[:id]
    @products = @cart.products.joins(:cart_products).where('cart_products.status != ?', "purchased")
    @total = @cart.cart_products.where("status != ?", "purchased").sum(:price)
  end

  def add_to_cart
  	cart = Cart.find params[:id]
  	product = Product.find params[:product_id]
  	cart_product = CartProduct.where('cart_id = ? and product_id = ? and status != ?', cart.id, product.id, "purchased" ).first
  	if cart_product.present?
  		quant = cart_product.quantity + 1
  		price = quant * product.price
  		cart_product.update_attributes(quantity: quant, price: price)
  	else
  		quantity = 1;
  		cart.cart_products.create(product_id: product.id, quantity: quantity, price: quantity*product.price, status: "active" )
  	end
  	cart_count = cart.cart_products.where('cart_products.status != ?', "purchased").sum(:quantity)
  	render text: "cart(#{cart_count})"
  end

  def edit_cart
    cart = Cart.find params[:id]
    product = Product.find params[:product_id]
    cart_product = CartProduct.where('cart_id = ? and product_id = ? and status != ?', cart.id, product.id, "purchased" ).first
    if params[:condition] == "quantity"
      cart_product.update_attributes(:quantity => params[:quantity], :price => params[:quantity].to_i*product.price)
    else
      cart_product.destroy
    end
    cart_count = cart.cart_products.where('status != ?', "purchased").sum(:quantity)
    cart_total = cart.cart_products.where('status != ?', "purchased").sum(:price)
    render :json => { :attachmentPartial => render_to_string('carts/_product', :layout => false, :locals => { :product => product, :cart => cart }),:cartCount => cart_count, :cartTotal => cart_total }
  end

end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_product.html.erb
<div class="sec_<%= product.id %>">
	<%= image_tag('http://store.storeimages.cdn-apple.com/4973/as-images.apple.com/is/image/AppleInc/aos/published/images/i/ph/iphone6/silver/iphone6-silver-select-2014_GEO_US?wid=470&hei=556&fmt=png-alpha&qlt=95&.v=cdYkN0',:width => 100, :height => 100, :border => 0, :alt => '', :title => '') %><br/>
	<%= product.name %><br/>
	<%= product.product_details %><br/>
	<%= product.price %><br/>
	no:<%= select_tag "product_count", options_for_select([[1,1],[2,2],[3,3],[4,4],[5,5],[6,6],[7,7],[8,8],[9,9],[10,10]], product.cart_products.where(cart_id: cart.id).sum(:quantity)),:disabled => true,:class => "product_count_#{product.id}" %></br>
	<button type='button' class="remove_item remove_item_<%=product.id%>" style="display: none;" data-id="<%= product.id %>">Remove item</button><br/>
	<button type='button' class="edit_item edit_item_<%=product.id%>" data-id="<%= product.id %>">Edit</button><br/>
	<button type='button' class="cancel_changes cancel_changes_<%=product.id%>" style="display: none;" data-id="<%= product.id %>" >cancel changes</button><br/>
	<button type='button' class="save_item save_item_<%=product.id%>" style="display: none;"  data-id="<%= product.id %>" >save</button><br/>
</div>

app/views/carts/show.html.erb
<% @products.each do |product| %>
<%= render partial: 'product', locals: { product: product, cart: @cart} %> 
<% end %>
<h>total:<span class="price"><%= @total %></span></h>
<%= link_to('Checkout', new_order_path, :method => :get) %>
<!-- <button type='button' class="checkout">checkout</button><br/> -->
<script type="text/javascript">
	$(document).ready(function() {
		var cart_id = <%= current_user.cart.id %>;
		$(document).on('click', '.edit_item', function() {
			var data = $(this).attr('data-id');
			$('.remove_item_'+data).show();
			$('.save_item_'+data).show();
			$('.cancel_changes_'+data).show();
			$('.edit_item_'+data).hide();
			$('.product_count_'+data).prop('disabled', false);
		});

		$(document).on('click', '.cancel_changes', function() {
			var data = $(this).attr('data-id');
			$('.cancel_changes_'+data).hide();
			$('.remove_item_'+data).hide();
			$('.save_item_'+data).hide();
			$('.edit_item_'+data).show();
			$('.product_count_'+data).prop('disabled', 'disabled');
		});
		$(document).on('click', '.save_item', function() {  
			var data = $(this).attr('data-id');
			var quant = $('.product_count_'+data).val();
			cart_update(data, quant, "quantity");
		});

		$(document).on('click', '.remove_item', function() {  
			var data = $(this).attr('data-id');
			cart_update(data, null, "remove");
		});

		function cart_update(product_id , num, cond){
			$.ajax({
				url: "/cart/edit_cart",
				type: "POST",
				data: {id: cart_id, product_id: product_id, quantity: num, condition: cond},
				success: function(response){
					console.log(response);
		            if (cond == "quantity"){
		            	$(".sec_"+product_id).html(response['attachmentPartial']);
		            }
		            else{
		            	$(".sec_"+product_id).remove();
		            }
		            $(".cart").html("cart("+response['cartCount']+")");
		            $(".price").html(response['cartTotal']);
		          }
		        });
		}
	});

</script>