config/routes.rb
Rails.application.routes.draw do
  get 'carts/show'

  root 'products#index'
  resources :products
  resources :carts
  resources :orders

  post 'cart/add_to_cart' => 'carts#add_to_cart'
  post 'cart/edit_cart' => 'carts#edit_cart'
  devise_for :users, :controllers => { :registrations => 'users/registrations' }
  mount API::Root => '/'

end

app/models/product.rb
class Product < ActiveRecord::Base
	# belongs_to :category
	# has_many :orders, :through => :order_products
	# has_many :order_products


	has_many :carts, :through => :cart_products
	has_many :cart_products
	
	def price_name
	  [name, price].join(' ')
	end

	def self.by_letter(letter)
	  where("name LIKE ?", "#{letter}%").order(:name)
	end
end

app/controllers/api/v1/products.rb
module API
  module V1
    class Products < Grape::API
      version 'v1'
      format :json
 
      resource :products do
        desc "Return list of recent products"
        get do
          Product.all
        end
        desc "Return a product"
        # params do
        #   requires :id, type: String, desc: "ID of the 
        #     product"
        # end
        get ":id", root: "product" do
          Product.where(id: params[:id]).first!
        end
      end
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
	# before_action :authenticate_user!
	def index
		@categories = Category.all
	end

	def new
		@product = Product.new
		@cat = [["Select One", ""]]
		Category.all.each do |cat|
			@cat << [cat.name, cat.id]
		end

	end

	def create
		@product = Product.create(name: params[:product][:name], product_details: params[:product][:product_details], category_id: params[:product][:category_id], price: params[:product][:price])
		if @product
			redirect_to products_path
		else
			new_product_path
		end
	end

	def edit
		@cat = [["Select One", ""]]
		Category.all.each do |cat|
			@cat << [cat.name, cat.id]
		end
		@product = Product.find params[:id]
		
	end

	def update
		@product = Product.find params[:id]
		product = @product.update_attributes(name: params[:product][:name], product_details: params[:product][:product_details], category_id: params[:product][:category_id], price: params[:product][:price])
		if product
			redirect_to products_path
		else
			product_path(:id => @product)
		end
	end

	def show
		@product = Product.find(params[:id])
	end

	def destroy
		@product = Product.find params[:id]
		if @product.destroy
			redirect_to products_path
		else
			product_path(:id => @product)
		end
	end

end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/edit.html.erb
<%= form_for @product do |f| %>
<%= f.label :name %>:
      <%= f.text_field :name %><br/>
      <%= f.label :product_details %>:
      <%= f.text_area :product_details%><br/>
      <%= f.label :category %>:
      <%= f.select :category_id, options_for_select(@cat, @product.category_id) %><br/>
      <%= f.label :price %>:
      <%= f.number_field :price, :class => 'text_field', :step => 'any'%><br/>
      <%= f.submit "Edit" %>
    <% end %>

app/views/products/index.html.erb
<div id="tabs">
  <ul>
  <% n = 1 %>
  <% m = 1 %>
  <% @categories.each do |category| %>
    <li><a href="#tabs-<%= n %>"><%= category.name %></a></li>
    <% n = n + 1 %>
  <% end %>
  </ul>
  <% @categories.each do |category| %>
  
  <div id="tabs-<%= m %>">
  <% category.products.each do |product| %>
  <%= link_to image_tag('http://store.storeimages.cdn-apple.com/4973/as-images.apple.com/is/image/AppleInc/aos/published/images/i/ph/iphone6/silver/iphone6-silver-select-2014_GEO_US?wid=470&hei=556&fmt=png-alpha&qlt=95&.v=cdYkN0',:width => 100, :height => 100, :border => 0, :alt => '', :title => ''), product_path(:id => product) %><br/>
  <%= product.name %><br/>
  <%= product.product_details.html_safe %><br/>
  <%= product.price %><br/>
  <% if current_user.present? && current_user.role.name == "admin"%>
    <%= link_to "Edit Product", edit_product_path(product) %>
  <% end %>
  <% end%>
  </div>
    <% m = m + 1 %>
  <% end %>
  
</div>
   <script>
  $( function() {
    $( "#tabs" ).tabs();
  } );
  </script>

app/views/products/new.html.erb
<%= form_for @product do |f| %>
<%= f.label :name %>:
      <%= f.text_field :name %><br/>
      <%= f.label :product_details %>:
      <%= f.text_area :product_details%><br/>
      <%= f.label :category %>:
      <%= f.select :category_id, options_for_select(@cat) %><br/>
      <%= f.label :price %>:
      <%= f.number_field :price, :class => 'text_field', :step => 'any'%><br/>
      <%= f.submit "Create" %>
    <% end %>

app/views/products/show.html.erb
<%= image_tag('http://store.storeimages.cdn-apple.com/4973/as-images.apple.com/is/image/AppleInc/aos/published/images/i/ph/iphone6/silver/iphone6-silver-select-2014_GEO_US?wid=470&hei=556&fmt=png-alpha&qlt=95&.v=cdYkN0',:width => 100, :height => 100, :border => 0, :alt => '', :title => '') %><br/>
  <%= @product.name %><br/>
  <%= @product.product_details %><br/>
  <%= @product.price %><br/>
  <a href="#" class="cart_click">add to cart</a>
  <script type="text/javascript">
  
  var pro_id = <%= @product.id %>;
  var usr = "<%= current_user %>";
  <% if !current_user.present? %>
    $('.cart_click').click(function() {
        alert("please login");

        });
  <% elsif current_user.role.name !="admin" %>
  var cart_id = <%= current_user.cart.id %>;
      $('.cart_click').click(function() {        
          $.ajax({
          url: "/cart/add_to_cart",
          type: "POST",
          data: {id: cart_id, product_id: pro_id},
          success: function(response){
            $(".cart").html(response)
          }
        });
          });
  <% end %>


  </script>